import '../home_4_driver_screen/widgets/cardetails_item_widget.dart';import 'package:flutter/material.dart';import 'package:link_click/core/app_export.dart';import 'package:link_click/widgets/app_bar/appbar_leading_image.dart';import 'package:link_click/widgets/app_bar/custom_app_bar.dart';import 'package:link_click/widgets/custom_elevated_button.dart';class Home4DriverScreen extends StatelessWidget {const Home4DriverScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 31.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Toyota Corolla", style: theme.textTheme.headlineSmall), SizedBox(height: 1.v), Row(children: [SizedBox(height: 22.adaptSize, width: 22.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgStar1, height: 22.adaptSize, width: 22.adaptSize, radius: BorderRadius.circular(1.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgStar2, height: 22.adaptSize, width: 22.adaptSize, radius: BorderRadius.circular(1.h), alignment: Alignment.center)])), Container(height: 21.v, width: 118.h, margin: EdgeInsets.only(left: 8.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("4.9 (531 reviews)", style: CustomTextStyles.titleSmallGray40001)), Align(alignment: Alignment.center, child: Text("4.9 (531 reviews)", style: CustomTextStyles.titleSmallGray40001))]))]), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgPictureHolder, height: 171.v, width: 309.h), SizedBox(height: 22.v), _buildCarDetails(context), SizedBox(height: 49.v), CustomElevatedButton(text: "Confirm the details", margin: EdgeInsets.only(left: 37.h, right: 36.h), onPressed: () {onTapConfirmTheDetails(context);}, alignment: Alignment.center), SizedBox(height: 6.v), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTxtEdit(context);}, child: Text("Edit", style: CustomTextStyles.titleMediumPrimary))), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.fromLTRB(11.h, 15.v, 289.h, 15.v), onTap: () {onTapVector(context);})); } 
/// Section Widget
Widget _buildCarDetails(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 9.h, right: 13.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 8.v);}, itemCount: 4, itemBuilder: (context, index) {return CardetailsItemWidget();}))); } 
/// Navigates to the home3DriverScreen when the action is triggered.
onTapVector(BuildContext context) { Navigator.pushNamed(context, AppRoutes.home3DriverScreen); } 
/// Navigates to the home3DriverScreen when the action is triggered.
onTapConfirmTheDetails(BuildContext context) { Navigator.pushNamed(context, AppRoutes.home3DriverScreen); } 
/// Navigates to the home41DriverScreen when the action is triggered.
onTapTxtEdit(BuildContext context) { Navigator.pushNamed(context, AppRoutes.home41DriverScreen); } 
 }
